management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091
  tomcat:
    threads:
      max: 500

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mini

mini:
  weixin:
    appId: wx6058db1a716236bc
    appSecret: a7481beaef239a5463e7975b6d373b37
#    appId: wx9f7210679a76509d
#    appSecret: e8a19fe3433bc2f19a76fe4e7925bc11