
wishes:
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: webdav
    webdav:
      url: http://122.9.38.18//webdav/
      directory: goods
      username: dev
      password: Wishes12345678