management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8092
  tomcat:
    threads:
      max: 500

logging:
  level:
    com:
      alibaba:
        nacos: warn

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: goods-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mini
wishes:
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: webdav
    webdav:
      url: http://122.9.37.63/webdav/
      directory: goods
      username: dev
      password: Wishes12345678
      replaceStr: /webdav

mini:
  goods:
    categoryList:
      - 瓜果
      - 蔬菜
      - 粮油
      - 禽类
      - 畜牧
      - 水产
