management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 172.16.4.136
  autoconfigure:
    exclude:
      - cn.edu.xmu.mini.core.config.CorsConfig
      - cn.edu.xmu.mini.core.config.SwaggerConfig
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: 用户中心
#          uri: lb://user-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user/**, /admin/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}

        - id: 商品中心
#          uri: lb://goods-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/goods/**
          filters:
            - RewritePath=/goods/?(?<segment>.*), /$\{segment}

  redis:
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000
    host: 127.0.0.1
